version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
    container_name: hurikane-frontend
    ports:
      - "${REACT_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped
    
  backend:
    build:
      context: ./backend
    container_name: hurikane-backend
    ports:
      - "${PORT}:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: hurikane-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "hurikane-cluster"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  postgres-data:
  kafka_data:

# kafka:
#   image: bitnami/kafka:latest
#   container_name: kafka
#   ports:
#     - "9092:9092"
#   environment:
#     KAFKA_KRAFT_CLUSTER_ID: "my-cluster"
#     KAFKA_CFG_NODE_ID: 1
#     KAFKA_CFG_PROCESS_ROLES: broker,controller
#     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#     KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
